### ISSUE TITLE
[Priority] Web to case forms not redirecting to correct confirmation page

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#100]
Quoted from our service team:

When the reseller order form at Librestream.com/reseller-orders is submitted, you are supposed to get forwarded to https://librestream.com/form-confirmations/registration-submitted

Which is now throwing a 404. Instead you are forwarded to https://webto.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8 which is incorrect.

Also, the opportunity registration form at https://librestream.com/register-opportunity/ is supposed to send you to https://librestream.com/form-confirmations/registration-submitted once you’ve submitted the form.  This is also returning a 404.

We need to get these fixed asap.

**Comment by samyue888** [comment]
Please refer to this old page as an example. It goes to the correct page when you click submit.
https://librestream.kinsta.cloud/register-opportunity/

**Comment by paulstroot** [comment]
I took a look at these forms. I noticed that the return url in the form was set to "cms.librestream.com..." instead of "librestream.com...", Also, it was missing a trailing slash at the end of the URL. I fixed these things. @samyue888 , could you please test the forms now?

 If you are still having trouble with the forms after my changes mentioned above let me know. We are a little restricted on what we can do on our end without access to SalesForce.

**Comment by samyue888** [comment]
@paulstroot This form is still redirecting to an empty link: https://librestream.com/register-opportunity/

**Comment by paulstroot** [comment]
@samyue888 - I think I may not have finished clicking "save" in WordPress. Give it a shot in about 10 minutes.

**Comment by samyue888** [comment]
@paulstroot Sorry, one more change. Could you please redirect the form on this page:
https://librestream.com/reseller-orders/
to
https://librestream.com/form-confirmations/order-submitted/

Thanks

**Comment by paulstroot** [comment]
@samyue888 - Yes. Update made.

**Comment by samyue888** [comment]
Thanks!
