### ISSUE TITLE
[Priority] None of the items are showing up 

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#109]
For this page, we want to link to a pdf, video, or page, and we've selected some examples in the 'Items' section, but none are showing up.

https://cms.librestream.com/wp-admin/post.php?post=12748&action=edit

**Comment by samyue888** [comment]
@paulstroot It seems this page is blocking all other updates in WP, so please address this first when you get a chance. Thanks!

**Comment by paulstroot** [comment]
I believe this is already possible, but it's a little bit confusing to find where to edit this in the admin. The "items" field when editing the page "Partner Sales Training" should point to a support page. When you last edited, you were able to add any type of page. but I have now tried restricting this so that you can only add the proper type of support page that will show some corresponding pages, PDFs or videos.

On the support page that you select, when you edit it, there is a section down near the bottom of the page labeled "Links", this is where you can designate which Videos, PDFs or Pages will show up. 

These are two pages with the same functionality that you may want to look at for reference.
https://librestream.com/training-deployment-adoption-materials/
https://librestream.com/remote-expert-ap-training-materials/

Try that out. If it turns out you need some different or additional functionality for the "Partner Sales Training" page please let us know.

NOTE: There is a bug on the live site that keeps the site from building if there are pages selected that are NOT support pages. I uploaded a fix to the development site that should hopefully fix this. This might be a good thing to push to the live site if we need some more time to work out the finer details of this page.

**Comment by samyue888** [comment]
@paulstroot Note that the current working page is linking to this support page 'partner resource test':
https://cms.librestream.com/wp-admin/post.php?post=12666&action=edit
![image](https://user-images.githubusercontent.com/81642726/116932846-a22cc380-ac17-11eb-86ca-7b21e9772e83.png)
But none of the resources are clickable, even though they are linked correctly in WP.

**Comment by samyue888** [comment]
@paulstroot Here is the page using the same format as the reference pages:
https://librestream.com/partner-sales-training/

Note that the PDF and video are not loading properly.

**Comment by samyue888** [comment]
Same with this duplicate training page, in which I created a test section at the bottom. The PDF and video are not showing:
https://librestream.com/training-deployment-adoption-materials-2/
![image](https://user-images.githubusercontent.com/81642726/116939263-ecff0900-ac20-11eb-8758-34357d0cf981.png)
![image](https://user-images.githubusercontent.com/81642726/116939287-f4261700-ac20-11eb-92dd-113bbc20d44e.png)

**Comment by paulstroot** [comment]
Thanks Sam. Did the comment I sent earlier make sense. I think the links and videos you're mentioning above are just some sample content and can't be expected to work properly. Once the update on development is pushed to the live site I think you should be able to add some actual links to these pages and hopefully they will work as expected.

If it's easier we can do a call to talk this through.

**Comment by samyue888** [comment]
I've merged the PR and the media files are showing now, thanks
