### ISSUE TITLE
Gatsby warnings

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#122]
We are getting this warnings when building:
![image](https://user-images.githubusercontent.com/81642726/118184564-5c7ab280-b3f0-11eb-81b8-5a4ac888c9b2.png)

**Comment by paulstroot** [comment]
It looks like the "non-page component" warnings are for templates that are not being used. This will not cause any issues. I can delete those template files if you'd like to clean things up, but it won't affect the site at all.

The "Found a Duplicate ID in WordPress" I haven't found an exact cause for yet. I did some research and is often related to an issue with how WordPress exposes multiple languages of the same page. This is different from our issue because we are not doing any language translations, but it does hint to us that it should not affect anything with the final website. I can keep digging further into this to try to eliminate the warning if you like, just let me know.

The "Query takes too long" warning is something we're looking into. I think it has something to do with large images being pulled from WordPress. This is only a warning and does not seem to be affecting the final build, but we will see if we can find a solution to remove the warning. I'm experimenting with making the WordPress original images sizes smaller.
