### ISSUE TITLE
iPhone Safari issues - many items not showing or clickable

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#129]
Here are some issues experienced by a colleague using Safari on iphone 6 iOS 12.5.3

None of the top menu items are clickable
None of the footer links are clickable
None of the CTA buttons are clickable
Many images are not showing

**Comment by paulstroot** [comment]
I'm seeing the same issues on old version of mobile safari that we were seeing on Internet Explorer in issue #113. These are likely related (the missing images issue is definitely the same issue). This issue is still waiting for review and approval. There was a question of this fixing causing a "serve images in next-gen formats" flag in Google Pagespeed insights, but with "next-gen" image formats, we need to either choose to support old browsers, or use these formats, we can't really have both.

**Comment by samyue888** [comment]
Understood. Is there a way to save the current build that address the 'next-gen' issue? So that we can revert back to this if needed

**Comment by paulstroot** [comment]
We have all of our code history saved in Github here, so we'll have a record of all changes. If we save our development for this we will be able to see exactly what and where the change were made so that we can change back whenever we decide it's time to stop supporting legacy browsers.

We will also make sure to test very thoroughly first though before pushing it to production.

**Comment by samyue888** [comment]
Waiting for our colleague with the iPhone to test. Will update you asap.

**Comment by samyue888** [comment]
Fixed, thanks
