### ISSUE TITLE
Heading is not showing for new page

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#134]
For this page:
https://cms.librestream.com/wp-admin/post.php?post=14271&action=edit

We'd like to have the following text in the banner 
![image](https://user-images.githubusercontent.com/81642726/121573114-b6639d80-c9d9-11eb-8b33-a06ccb67f471.png)

But instead, we're getting this 'Scale Knowledge....' text, which doesn't even exist on the page, so there's no way to edit or delete it.
![image](https://user-images.githubusercontent.com/81642726/121573217-d85d2000-c9d9-11eb-9c7b-b6b95d0311aa.png)

**Comment by samyue888** [comment]
Also, the background image for the banner is not showing:
![image](https://user-images.githubusercontent.com/81642726/121574322-fecf8b00-c9da-11eb-875d-3139dfd4f307.png)

**Comment by paulstroot** [comment]
Okay.  A couple things going on here. First of all, for some reason the default page template has two sections in the admin for the hero. One at the top labeled "Hero", and one below that labeled "Template- Default". For this page you want to enter in your Hero text and image in the "template default" section. I did this and it is showing up. To make the text fit I wrapped the headline in a <span> tag to make it a little smaller. I also split this up into a headline and description to make it look a little nicer, but I do not know what the text says, so I'm not quite sure if this is a logical split. You can edit this as you see fit.

The second thing is the background image. There was actually a bug keeping background images from showing up in the default template. I have fixed this and I will create a Pull Request for it shortly.

Regarding the hero image, you can see how it looks on the development site
https://librestreamdevelop.gatsbyjs.io/free-demo-jp/
You're going to want to give it a faded blue treatment like the images on the platform pages so that the text overlay can be read.

**Comment by samyue888** [comment]
That's perfect, thanks!

**Comment by paulstroot** [comment]
@samyue888 - I just created a pull request so you can get that background image fix into the main branch.
