### ISSUE TITLE
[Urgent] This blog post is not showing up

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#147]
@paulstroot 

The following HCL blog shows a page not found when clicked:
![image](https://user-images.githubusercontent.com/81642726/126014585-a7a8d757-9e08-4781-8720-396dfcd14184.png)
https://librestream.com/blog/hcl%e2%80%90and%e2%80%90librestream%e2%80%90offering%e2%80%90critical%e2%80%90remote%e2%80%90it%e2%80%90services%e2%80%90across%e2%80%90industries/
![image](https://user-images.githubusercontent.com/81642726/126014607-d3bdd800-8ea9-4eba-91c8-4414fdbaeead.png)

We've already checked that the content is correct and manually rebuilt.

**Comment by paulstroot** [comment]
@samyue888 - This has been fixed

The page in the WordPress CMS had a URL slug that contained HTML special characters instead of dashes. You can see this in the URL that you pasted above in this issue. The browser was never able to actually visit this URL because it converted the special characters to dashes when you go to the page. This happens sometimes if text is coped and pasted from another source like a text editor or micorsoft Word (or perhaps other reasons I'm unaware of ). I fixed this by simply re-typing the URL slug for the page in the WordPress CMS and re-building the site.

**Comment by samyue888** [comment]
Perfect, thank you @paulstroot !
