### ISSUE TITLE
Implement sandbox that collects updates and pushes daily (beginning of next day)

### ISSUE THREAD

**Issue by samyue888** [ocupop/librestream#91]

**Comment by tbeck** [comment]
@samyue888 - We are holding on any recommendations here as we better understand the ideal workflows and typical content management activity.

**Comment by samyue888** [comment]
@tbeck Are you able to recommend best practices for this procedure?

CC @lsdrew

**Comment by tbeck** [comment]
@samyue888 - We are looking into the options here and tracking the average number of builds per day to get a better sense of expected activity and possible points of control before making a recommendation.

We will get back to you shortly with our recommendations.

**Comment by paulstroot** [comment]
@samyue888 - Can you explain a little about why you would like the updates to be made daily? If it's so you can work on multiple edits to the site, and have them pushed all at once would a "deploy" button in the CMS work for you? That would give you total control over when the updates are pushed to the live site. A daily automated push is also an option, but I'd like to know first which solution best solves the issue you are addressing. 

If the number of updates made to the site on a daily basis is a concern, Tom is checking into that as he mentioned above.

**Comment by samyue888** [comment]
@paulstroot The idea of a collection of updates pushed daily stemmed from a potential concern of multiple updates in WP breaking the gatsby build, or potentially breaking a page (eg. changing content on the support page caused it to go blank previously). Would these issues still occur? If so, we'd like to collect all WP updates in a development site, previewable by our team to ensure nothing is broken, before auto-pushing the next morning. We chose daily as that seemed like the right frequency for our work schedule and post frequency, but please let us know if there is a best practice. We would definitely need a manual 'deploy' button in addition to auto-pushing daily.

**Comment by paulstroot** [comment]
@samyue888 and @lsdrew - Here is the solution that we came up with. Let us know if you think this will work for you. We have created another Gatsby Cloud site named "Staging" that builds off of the same "main" codebase. We can then set this up so that every time you make a change in the WordPress CMS, the staging site is updated and you can view your current changes. (I will put a "View Staging Site" in the WordPress admin bar to jump straight to the staging site). When everything looks good on staging, you can click the "Deploy site" button in the CMS admin bar to publish everything to the live site.

![image](https://user-images.githubusercontent.com/52838369/117494698-51300e80-af3a-11eb-8668-5ffe067200d2.png)

I don't think a daily automated build would be necessary, since nothing is posted to staging automatically. The person who makes the staging changes could easily just deploy their changes after they check them. It is possible though if you think it's something you would like to do.

**Comment by samyue888** [comment]
Thanks @paulstroot. Let's book a call with Drew to discuss

**Comment by paulstroot** [comment]
@samyue888 - Please review this so far.

I've created a "deploy" button in the admin bar on our staging WordPress site. This is mostly so you can see how it looks. It does function, but it only deploys to one of our development branches. Here is the staging site admin link:
https://staging-librestreamcms.kinsta.cloud/wp-admin/ (same login credentials as the live CMS site.)

You'll see when you hover over the "deploy" button that there are three options, "Deploy to live", "View Staging Site" and "View GatsbyJS Build Status"

 - Deploy to live will trigger a build on the live site. When all is completed, this will be the ONLY way to push WordPress changes to the live site (except, of course, for manually triggering a build in GatsbJS)
 - View Staging site will take you to the home page of the staging site. This is slightly different from clicking "Preview" when editing a page or post. When you click "preview", you are viewing unsaved changes to the page you are working on. Clicking "View Staging Site" will take you to a version of the site with all recent saved changes that have been made in WordPress, even ones that have not been published to the live site.
 - Clicking "View GatsbyJS Build Status" will take you straight to the GatsbyJS site to the status of your build. When you click the "Deploy to Live button", the button label will change to "Success" right away, telling you that a build was triggered, but a build may take several minutes. If you want to see the build status to check whether it built successfully, you can view this directly on the GatsbyJS site.

Does all of this make sense so far? Let me know if you have any questions. When I push this to the live CMS site, I will update the settings so that saving changes on pages will build on the staging site, not the live site.

**Comment by samyue888** [comment]
It makes sense, thanks. Before pushing this, we'd like to see the plugin that can log updates, as discussed in the meeting.

**Comment by paulstroot** [comment]
@samyue888 - There are a number of activity log plug-ins for wordpress out there. I installed three of them on a staging site so you can take a look and see if one of them will meet your needs.

1) **Sucuri plugin**. This is a plug-in I often use for it's security features, but it also keeps a user activity log. It's a pretty simple log, mostly recording if an update has been made to a page, but not indicating what the change was. This type of log might best be used for security reasons, not so much for keeping detailed track of changes to the site. You can view it here:
https://staging-librestreamcms.kinsta.cloud/wp-admin/admin.php?page=sucuriscan#auditlogs

2) **Simple History**. This one looks like it keeps a little bit more detailed track of page and post updates. The updated page is linked to so you could then view the revision history of that page. 
https://staging-librestreamcms.kinsta.cloud/wp-admin/index.php?page=simple_history_page

3) **ActivityLog Plug-in**. I like the interface of this one the best so far. It's especially nice that you can filter the activity results because they build up very fast. Like the other plug-in, it does not show what the change to the page was directly, but it links to the page, where you can then view revision history. This would probably be my recommendation. Here's a link to it in the admin
https://staging-librestreamcms.kinsta.cloud/wp-admin/admin.php?page=activity_log_page

**Comment by samyue888** [comment]
@paulstroot Simple History looks great. Let's go with that.

**Comment by paulstroot** [comment]
I have added it to the live CMS site.
https://cms.librestream.com/wp-admin/index.php?page=simple_history_page

**Comment by samyue888** [comment]
@paulstroot Please go ahead and implement the deploy function to the current WP. Thanks

**Comment by paulstroot** [comment]
Will do. I will be mostly unavailable tomorrow, and out of the office for
the holiday on Monday. I would feel best pushing this live when I will be
around to troubleshoot any questions or emergencies. Is next week okay?

**Comment by paulstroot** [comment]
This has been implemented. You can now make changes to the WordPress CMS all day long, and all of your saves will be built on the "staging branch". To view the staging site you can go to "Deploy -> View Staging Site" in the top admin bar. Changes will be pushed to the live site only when you click "Deploy -> Deploy to Live".

Once you click "Deploy to live", you may want to then go to "Deploy -> View GatsbyJS Build Status" to confirm that it builds properly. If not, just click the deploy button again. We have an open issue to resolve these failed builds.)

![image](https://user-images.githubusercontent.com/52838369/120355327-d522af80-c2c8-11eb-9827-f4fcd472b0ae.png)


FYI, I am still working with Gatsby Cloud to try to get our preview button working.

**Comment by samyue888** [comment]
@paulstroot Testing on our CMS now, and clicking each of those buttons only opens the same page in a new tab. We cannot view the staging site or gatsby build.

**Comment by samyue888** [comment]
Note that the url doesn't redirect anywhere:
![image](https://user-images.githubusercontent.com/81642726/120379599-d78b0680-c2d4-11eb-8010-0a75fe08cf4e.png)
![image](https://user-images.githubusercontent.com/81642726/120379623-dfe34180-c2d4-11eb-9f91-d7851c5effea.png)

**Comment by paulstroot** [comment]
Try it now. Bug fixed.

**Comment by samyue888** [comment]
Thanks. Could you please explain what happens if I press trigger build for the staging site? 
![image](https://user-images.githubusercontent.com/81642726/120380996-c0e5af00-c2d6-11eb-9392-121bc9df6b29.png)
And what happens if I trigger build for the live site? Will all WP updates be pushed?
![image](https://user-images.githubusercontent.com/81642726/120381077-d8bd3300-c2d6-11eb-89a6-0f893eecbdf3.png)

**Comment by paulstroot** [comment]
That will build the staging site only, not the live site. Same as when you
save a post in the WordPress CMS. Does that make sense?

**Comment by samyue888** [comment]
Yes. Assuming we still have the image cache issue, I'll have to rebuild the staging site (instead of the live site) everytime someone publishes a post?

**Comment by paulstroot** [comment]
If that post has an image in it, then yes.

**Comment by samyue888** [comment]
Got it. And what happens if I trigger a build for the live site? Will all updates from the staging site be pushed?

**Comment by paulstroot** [comment]
Correct. Although, just to clarify the order of things, the staging site
and the live site are built directly off of the same codebase in github, so
the live site is not technically pushed from the staging to live. (a detail
that isn't necessarily that important on your end, just wanted to clarify
in case it caused any confusion later)

-Paul

**Comment by samyue888** [comment]
Thanks - Always great to clarify! The deploy to live button still doesn't seem to work.

**Comment by paulstroot** [comment]
I just checked it out and think I fixed the problem with the deploy to live
button.

**Comment by samyue888** [comment]
Could you add an option to schedule a deploy to the live site? We have previously scheduled press releases for early morning

**Comment by paulstroot** [comment]
Let's make this a new feature request. It will take some thought on how to
schedule this properly.
